// GENERATED by node scripts/build-finanz-domain-hook.mjs. Do not edit.
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Decimal = void 0;
exports.money = money;
exports.sumMoney = sumMoney;
exports.subMoney = subMoney;
exports.mulMoney = mulMoney;
exports.percentOf = percentOf;
exports.bruttoFromNetto = bruttoFromNetto;
exports.nettoFromBrutto = nettoFromBrutto;
exports.roundMoney = roundMoney;
exports.moneyToString = moneyToString;
exports.formatMoneyDe = formatMoneyDe;
const decimal_js_1 = __importDefault(require("../vendor/decimal.js"));
exports.Decimal = decimal_js_1.default;
/**
 * Geldbeträge und Steuerberechnungen — nie native JS-Floats (ADR-0016).
 * Interne Repräsentation: Decimal mit 2 Nachkommastellen (EUR Cent-sicher).
 */
decimal_js_1.default.set({
    precision: 28,
    rounding: decimal_js_1.default.ROUND_HALF_UP,
});
function money(value = 0) {
    if (value instanceof decimal_js_1.default)
        return value;
    if (typeof value === "string" && value.trim() === "") {
        return new decimal_js_1.default(0);
    }
    return new decimal_js_1.default(value);
}
/** Summe von Beträgen */
function sumMoney(...values) {
    return values.reduce((acc, v) => acc.plus(money(v)), money(0));
}
/** Differenz a − b */
function subMoney(a, b) {
    return money(a).minus(money(b));
}
/** Produkt (z. B. Menge × Preis) */
function mulMoney(a, b) {
    return money(a).times(money(b));
}
/**
 * Prozentanteil (z. B. 19 % USt auf Netto).
 * `rate` als Zahl: 19 für 19 %.
 */
function percentOf(base, rate) {
    return money(base).times(money(rate)).dividedBy(100);
}
/** Netto + USt → Brutto */
function bruttoFromNetto(netto, ustRate) {
    return money(netto).plus(percentOf(netto, ustRate));
}
/** Brutto → Netto bei bekanntem USt-Satz */
function nettoFromBrutto(brutto, ustRate) {
    const rate = money(ustRate);
    // netto = brutto / (1 + rate/100)
    return money(brutto).dividedBy(rate.dividedBy(100).plus(1));
}
/** Auf 2 Nachkommastellen (kaufmännisch) runden */
function roundMoney(value, decimals = 2) {
    return money(value).toDecimalPlaces(decimals, decimal_js_1.default.ROUND_HALF_UP);
}
/** Serialisierung für DB/API (string, 2 Stellen) */
function moneyToString(value, decimals = 2) {
    return roundMoney(value, decimals).toFixed(decimals);
}
/** Anzeige de-DE (1.234,56) ohne Währungssymbol */
function formatMoneyDe(value, options) {
    var _a;
    const decimals = (_a = options === null || options === void 0 ? void 0 : options.decimals) !== null && _a !== void 0 ? _a : 2;
    const n = roundMoney(value, decimals).toNumber();
    const formatted = new Intl.NumberFormat("de-DE", {
        minimumFractionDigits: decimals,
        maximumFractionDigits: decimals,
    }).format(n);
    if (options === null || options === void 0 ? void 0 : options.currency) {
        return `${formatted}\u00a0€`;
    }
    return formatted;
}
