// Generate the PB copy from the reviewed TypeScript contract, no second tax implementation.
import ts from '../app/node_modules/typescript/lib/typescript.js';
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
const source = new URL('../app/src/modules/expenses/reverse-charge.ts', import.meta.url);
const target = new URL('../pocketbase/pb_hooks/reverse-charge.js', import.meta.url);
const output = '// GENERATED by node scripts/build-rc-hook.mjs. Do not edit.\n' + ts.transpileModule(readFileSync(source, 'utf8'), { compilerOptions: { target: ts.ScriptTarget.ES2017, module: ts.ModuleKind.CommonJS, esModuleInterop: true } }).outputText.replace('require("decimal.js")', 'require("./vendor/decimal.js")');
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== output || readFileSync(new URL('../pocketbase/pb_hooks/vendor/decimal.js', import.meta.url), 'utf8') !== readFileSync(new URL('../app/node_modules/decimal.js/decimal.js', import.meta.url), 'utf8') || readFileSync(new URL('../pocketbase/pb_hooks/vendor/decimal-LICENCE.md', import.meta.url), 'utf8') !== readFileSync(new URL('../app/node_modules/decimal.js/LICENCE.md', import.meta.url), 'utf8')) throw new Error('RC hook or Decimal copy is stale');
} else {
  writeFileSync(target, output);
  mkdirSync(new URL('../pocketbase/pb_hooks/vendor/', import.meta.url), { recursive: true });
  for (const [src, dest] of [['decimal.js', 'decimal.js'], ['LICENCE.md', 'decimal-LICENCE.md']]) copyFileSync(new URL('../app/node_modules/decimal.js/' + src, import.meta.url), new URL('../pocketbase/pb_hooks/vendor/' + dest, import.meta.url));
}
